
# Description

# PR - Ignore symbolic links pointing outside of the root directory

Within the structure of files to analyze, if there is a symbolic link pointing to a file or a directory outside of the root directory, this symlink is now ignored, as it appears to be out of the scope of the analyzed project.

This PR fixes #338.

# Issue #338 - Crash if there is a symlink to a resource outside of the root directory

Hello there, thank you for this great tool!

Black crashes when it finds a symbolic link pointing to a file or a directory outside of the root directory.

Steps to reproduce

Create the following structure:
base
  |-- repo
  |     |-- dummy.py
  |     `-- resource -> ../resource
  `-- resource
Initiate base/repo as a Git repository (so as to set the root directory);
Call black . within base/repo;
Expected behavior: Black ends as expected;
Current behavior: throws an exception:
Traceback (most recent call last):
  File "/home/neraste/.virtualenvs/test_black/bin/black", line 11, in <module>
    sys.exit(main())
  File "/home/neraste/.virtualenvs/test_black/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/neraste/.virtualenvs/test_black/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/neraste/.virtualenvs/test_black/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/neraste/.virtualenvs/test_black/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/neraste/.virtualenvs/test_black/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/neraste/.virtualenvs/test_black/lib/python3.6/site-packages/black.py", line 347, in main
    gen_python_files_in_dir(p, root, include_regex, exclude_regex, report)
  File "/home/neraste/.virtualenvs/test_black/lib/python3.6/site-packages/black.py", line 2942, in gen_python_files_in_dir
    normalized_path = "/" + child.resolve().relative_to(root).as_posix()
  File "/usr/lib64/python3.6/pathlib.py", line 872, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/data/test_black/base/resource' does not start with '/data/test_black/base/repo'
As pointed out in the backtrace, this is due to the line 2942, where the resolved path of the files is made relative to the root directory. This is indeed impossible if the file is outside of the root directory. One can wonder if it makes sense to have an external link within a repository, but, well I am in this case.

Adding the conflicting file/folder to the exclude list does not work.

Possible workaround

A possible workaround could be to simply ignore this case and do not handle this simlinked resource:

        try:
            normalized_path = "/" + child.resolve().relative_to(root).as_posix()

        except ValueError:
            if child.is_symlink():
                continue                                                        

            raise
Additional information

Operating system: GNU/Linux OpenSUSE Tumbleweed
Python version: 3.6
Black version: 18.6b2
Does also happen on master: yes

# Diff

diff --git a/black.py b/black.py
index 9d9bada..e3b3882 100644
--- a/black.py
+++ b/black.py
@@ -2941,11 +2941,22 @@ def gen_python_files_in_dir(
     """Generate all files under `path` whose paths are not excluded by the
     `exclude` regex, but are included by the `include` regex.
 
+    Symbolic links pointing outside of the root directory are ignored.
+
     `report` is where output about exclusions goes.
     """
     assert root.is_absolute(), f"INTERNAL ERROR: `root` must be absolute but is {root}"
     for child in path.iterdir():
-        normalized_path = "/" + child.resolve().relative_to(root).as_posix()
+        try:
+            normalized_path = "/" + child.resolve().relative_to(root).as_posix()
+        except ValueError:
+            if child.is_symlink():
+                report.path_ignored(
+                    child,
+                    "is a symbolic link",
+                )
+                continue
+
+            raise
+
         if child.is_dir():
             normalized_path += "/"
         exclude_match = exclude.search(normalized_path)
